info:
  contact: {}
paths:
  /api/v1/:
    get:
      description: Rota raiz da API v1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Página inicial
      tags:
      - Home
  /api/v1/users:
    get:
      description: Retorna todos os usuários cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Listar usuários
      tags:
      - Users
swagger: "2.0"
